iphone_amema:
  image: node
  working_dir: /usr/src/app
  command: node bot.js
  volumes:
    - ./iphone_amema/:/usr/src/app
  links:
    - redis
amema_memes:
  image: node
  working_dir: /usr/src/app
  command: node bot.js
  volumes:
    - ./amema_memes/:/usr/src/app
    - ./corpus/:/data
  links:
    - redis
application_amema:
  build: ./application_amema/
  links:
    - redis
laptop_amema:
  image: node
  working_dir: /usr/src/app
  command: node bot.js
  volumes:
    - ./laptop_amema/:/usr/src/app
  links:
    - redis
redis:
  image: redis
  command: redis-server /usr/local/etc/redis/redis.conf
  volumes:
    - ./redis.conf:/usr/local/etc/redis.conf
